### ISSUE TITLE
Welcome back Ender, Please return to Discord if you can

### ISSUE THREAD

**Issue by koap1** [EnderTheCoder/stardust-forge#2]

**Comment by TechTastic** [comment]
Or use that Matrix client Delta uses

**Comment by ewoudje** [comment]
Bruh

**Comment by EnderTheCoder** [comment]
> 
I'm struggling with discord's "I'm not a robot". It should be the problem with my new proxy server IP address.

**Comment by Rubydesic** [comment]
Maybe try matrix https://matrix.to/#/#valkyrien-skies:matrix.org
